name: publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install topo-metrics with publish dependencies
        run: pip install -e ".[publish]"
      - name: Build
        run: python -m build
      - name: Check
        run: twine check dist/*
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}