name: Tests
on: [push]
permissions:
    contents: read
jobs:
    tests:
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
                os: ['ubuntu-latest', 'macos-latest']
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Upgrade pip
              run: |
                  python -m ensurepip --upgrade
                  python -m pip install --upgrade pip setuptools wheel

            - name: Install ruff
              run: pip install ruff==0.11.0

            - name: Run ruff
              run: ruff check src tests

            - name: Install topo-metrics
              run: pip install -e ".[tests]"

            - name: Run tests
              run: pytest tests --cov=src/topo_metrics --cov-report=xml

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}